<a href="https://colab.research.google.com/github/Tonantzintla-618/data-science/blob/main/Kopia_notatnika_template.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.22.4'

In [ ]:
print(dir(np))

In [ ]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [ ]:
x = np.array([1, 3])
print(x) 

[1 3]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.ndin

AttributeError: ignored

In [ ]:
x.ndim

1

In [ ]:
x.shape

(2,)

In [ ]:
x.size

2

In [ ]:
x.dtype

dtype('int64')

In [ ]:
np.array([1.3, 2.3, 1.4])

array([1.3, 2.3, 1.4])

In [ ]:
x = np.array([1.3, 2.3, 1.4])

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.dtype

dtype('float64')

In [ ]:
lol

NameError: ignored

In [ ]:
clear

In [ ]:
np.array([[1, 2], [-3 , 1]])

array([[ 1,  2],
       [-3,  1]])

In [ ]:
X = np.array([[1, 2], [-3, 1]])


In [ ]:
PRINT(X)

NameError: ignored

In [ ]:
print(x)

[1.3 2.3 1.4]


In [ ]:
x.shape

(3,)

In [ ]:
X.shape

(2, 2)

In [ ]:
x = np.array([[1, 2, 4], [4, 2 ,1]])

In [ ]:
print(x)

[[1 2 4]
 [4 2 1]]


In [ ]:
x.shape

(2, 3)

In [ ]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2 ,1]]]
     
)
x


array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [ ]:
x.ndim

3

In [ ]:
x,shape

NameError: ignored

In [ ]:
x.shape

(2, 2, 3)